UI menu.c32
PROMPT 0

MENU TITLE Exile OS Boot menu
TIMEOUT 10
DEFAULT Exile OS

LABEL Exile OS
    MENU LABEL Exile OS
    KERNEL mboot.c32
    APPEND ../Prekernel root=/dev/hda1 --- ../Kernel

LABEL Exile OSText
    MENU LABEL Exile OS (text mode)
    KERNEL mboot.c32
    APPEND ../Prekernel root=/dev/hda1 graphics_subsystem_mode=off --- ../Kernel

LABEL Exile OSNoACPI
    MENU LABEL Exile OS (No ACPI)
    KERNEL mboot.c32
    APPEND ../Prekernel root=/dev/hda1 acpi=off --- ../Kernel

LABEL Exile OSSerialDebug
    MENU LABEL Exile OS (with serial debug)
    KERNEL mboot.c32
    APPEND ../Prekernel root=/dev/hda1 serial_debug --- ../Kernel
