timeout: 3
wallpaper: boot():/wallpaper.png

/Exile OS (normal)
    protocol: multiboot1
    cmdline: root=block100:2
    path: boot():/Kernel

/Exile OS (text mode)
    protocol: multiboot1
    cmdline: graphics_subsystem_mode=off root=block100:2
    path: boot():/Kernel

/Exile OS (no ACPI)
    protocol: multiboot1
    cmdline: root=block100:2 acpi=off
    path: boot():/Kernel

/Exile OS (with serial output)
    protocol: multiboot1
    cmdline: root=block100:2 serial_debug
    path: boot():/Kernel
